#!/bin/bash

function createdb()
{

echo enter the name of your Database

read name

. ./validInput $name
res1=$?
if [ $res1 == 1 ]
then
. ./searchExistdir $name
res2=$?
if [ $res2 == 0 ]
then
mkdir $name
echo "$name created sucess "
elif [ $res2 == 1 ]
then 
echo "$name aready exist"
fi
elif [ $res1 == 2 ]
then	
echo space
else
echo "invalid input"
fi

return $res1

}

createdb 

